import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import * as React from "react";
import {Providers} from "./providers";
import SideBar from "@/components/SideBar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={`${inter.className} text-black`}>
        <Providers>
            <div className="grid grid-cols-10">
                <div className="col-span-2 border-r-2 border-slate-500/40 bg-zinc-200">
                    <SideBar/>
                </div>
                <div className={"col-span-8 bg-white"}>
                    {children}
                </div>
            </div>
        </Providers>
        </body>
        </html>
    );
}
